{% set name = "regional-mom6" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/regional_mom6-{{ version }}.tar.gz
  sha256: 54880bbd4ffd7de7e4b38de5e778a022ac75ccd37ef9f88f22f242f178044bcf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - bottleneck
    - dask-core
    - distributed
    - f90nml
    - netcdf4
    - numpy >=1.17.0
    - scipy >=1.2.0
    - xarray
    - xesmf >=0.8

test:
  imports:
    - regional_mom6
  commands:
    - pytest tests/
  source_files:
    - tests
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/COSIMA/regional-mom6
  summary: Automatic generation of regional configurations for Modular Ocean Model 6
  license: MIT
  license_file: LICENSE
  doc_url: https://regional-mom6.readthedocs.io/
  dev_url: https://github.com/COSIMA/regional-mom6

extra:
  recipe-maintainers:
    - angus-g
