{% set name = "regional-mom6" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/regional_mom6-{{ version }}.tar.gz
  sha256: 009485d4a04b99af543bd6b945f18cca15bf6e8f57946d667d69b7b3513b0f65

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - bottleneck
    - copernicusmarine >=2.0.0,<2.1.0
    - dask
    - f90nml >=1.4.1
    - mom6_forge >=0.3.0,<0.4.0
    - netcdf4
    - numpy
    - pint-xarray
    - ruamel.yaml
    - scipy >=1.2.0
    - xarray
    - xesmf

test:
  imports:
    - regional_mom6
  commands:
    - pytest tests/
  source_files:
    - tests
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/COSIMA/regional-mom6
  summary: Automatic generation of regional configurations for Modular Ocean Model 6
  license: MIT
  license_file: LICENSE
  doc_url: https://regional-mom6.readthedocs.io/
  dev_url: https://github.com/COSIMA/regional-mom6

extra:
  recipe-maintainers:
    - angus-g
