{% set name = "regional-mom6" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/regional_mom6-{{ version }}.tar.gz
  sha256: 50c4ced3df65af74013fbb720bb7e6920dce11f42d8ca18f61adb8ee8a55e147

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - bottleneck
    - dask-core
    - distributed
    - netcdf4
    - numpy >=1.17.0
    - scipy >=1.2.0
    - xarray
    - xesmf >=0.8

test:
  imports:
    - regional_mom6
  commands:
    - pytest tests/
  source_files:
    - tests
  requires:
    - pytest

about:
  home: https://github.com/COSIMA/regional-mom6
  summary: Automatic generation of regional configurations for Modular Ocean Model 6
  license: MIT
  license_file: LICENSE
  doc_url: https://regional-mom6.readthedocs.io/
  dev_url: https://github.com/COSIMA/regional-mom6

extra:
  recipe-maintainers:
    - angus-g
